[[service]]
name = "ping"
exec = [ "ping.sh" ]

[[service]]
name = "pong"
exec = [ "pong.sh" ]

[[consumer]]
consumes.stdout = "ping"
kind = "stdout"
# kind.log = "ping.txt"

[[consumer]]
consumes.stdout = "pong"
kind = "stdout"
# kind.log = "pong.txt"
